name: IndexNow Submission

on:
  push:
    branches:
      - main  # 设置为你推送代码的分支

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 设置为你使用的 Node.js 版本

    - name: Install dependencies
      run: npm install  # 如果你的项目需要安装依赖

    - name: Build site
      run: npm run build  # 如果你的项目需要构建，例如使用 Gatsby、Next.js 等

    - name: Get current timestamp
      id: date
      run: echo "::set-output name=timestamp::$(($(date +%s) ))"

    - name: Submit to IndexNow
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"key\":\"${{ secrets.INDEXNOW_KEY }}\",\"url\":\"https://zhaoguohui09820.github.io/index\",\"timestamp\":${{ steps.date.outputs.timestamp }}}}" \
          https://api.indexnow.org/indexnow
